site_name: Docs Hotkey
theme:
  name: readthedocs

nav:
  - Home: index.md
  - Usage: usage.md
  - Building from Source: source.md
  - About: about.md
  - Actions:
      - Styling Text: actions/text.md
      - Formatting Text: actions/page.md
      - Executing Add-ons: actions/addons.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables

extra_css:
  - assets/styles/youtube.css
  - assets/styles/styles.css
